<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ItemsLeft</name>
   <tag></tag>
   <elementGuidId>82208509-85c8-49f9-9c00-ebe30b62bc24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.todo-count</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
