<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TodoInput</name>
   <tag></tag>
   <elementGuidId>6174305a-c475-499e-8861-9e765724b226</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.new-todo</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
